=== HenrikTrom/flir_icp_calib/cfg/TransformsSettings.Scheme.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "online": { "type": "boolean" },
        "log": { "type": "boolean" },
        "load_path_offline": { "type": "string" },
        "camera_settings_file": { "type": "string" },
        "aruco_dictionary": { "type": "integer" },
        "h": { "type": "integer" },
        "w": { "type": "integer" },
        "min_markers": { "type": "integer" },
        "calibration_file": { "type": "string" },
        "min_cameras_per_point": { "type": "integer" },
        "local_pattern_file": { "type": "string" },
        "max_reprojection_error_images": { "type": "number" },
        "max_reprojection_error_robot": { "type": "number" },
        "parent_frame_id": { "type": "string" },
        "child_frame_id": { "type": "string" }
    },
    "required": [
        "online", "log",
        "load_path_offline", 
        "camera_settings_file",
        "aruco_dictionary", "h", "w",
        "min_markers",
        "calibration_file", 
        "min_cameras_per_point", 
        "local_pattern_file", 
        "max_reprojection_error_images",
        "max_reprojection_error_robot",
        "parent_frame_id", "child_frame_id"
    ]
  }

=== HenrikTrom/flir_icp_calib/cfg/TransformsSettings.json
{
    "online": true,
    "log": true,
    "load_path_offline": "/home/docker/catkin_ws/src/fri_transforms/test/data",
    "camera_settings_file": "/home/docker/workspace/workspace/src/flir_icp_calib/cfg/1024x768.json",
    "aruco_dictionary": 20,
    "h": 10,
    "w": 8,
    "min_markers": 10,
    "calibration_file": "/home/docker/workspace/workspace/src/flir_icp_calib/cfg/Calibration1024x768.json",
    "min_cameras_per_point": 3,
    "local_pattern_file": "/home/docker/workspace/workspace/src/flir_icp_calib/data/local_calibration.json",
    "max_reprojection_error_images": 2,
    "max_reprojection_error_robot": 5,
    "parent_frame_id": "cam0",
    "child_frame_id": "fr3_link0"
}
